
tasks:
  - init: "install dart"
    command: brew tap dart-lang/dart && brew install dart

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - Dart-Code.dart-code